[package]
name = "pahe-cli"
version = "0.0.1-alpha"
edition = "2024"

[dependencies]
clap.workspace = true
inquire.workspace = true
pahe.workspace = true
pahe-downloader.workspace = true
tokio.workspace = true
owo-colors.workspace = true
