[package]
name = "pahe-downloader"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm.workspace = true
reqwest.workspace = true
tokio.workspace = true
thiserror.workspace = true
owo-colors.workspace = true
